<?php

namespace App;

use Illuminate\Database\Eloquent\Model as baseModel;
use Illuminate\Support\Str;

class Model extends baseModel
{
    protected $guarded=[];

    public $incrementing=false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static ::creating(function ($model){
            $model->{$model->getKeyName()}=(string)Str::uuid();
        });
    }
}
